### ISSUE TITLE
Version r1.0.0.36 creates Soundcloud user folders

### ISSUE THREAD

**Issue by BenjaminKobjolke** [StephenCasella/SoundCloud-Playlist-Sync#6] opened 2015-05-04 12:24 UTC
The newest version creates a subfolder for every Soundcloud user when I download a playlist.
Previous versions just downloaded all songs into the "Local directory", the new version downloads them to "Local Directory"/"Soundcloud Username".

If this is a feature then there should be a way to disable it.

**Comment by StephenCasella** [comment] 2015-05-09 01:23
Thanks for creating this issue. The original versions of the downloader and its screenshot tutorial sorted the songs into artist folders just like the current version does. However, that functionality was accidentally broken in [this](https://github.com/StephenCasella/SoundCloud-Playlist-Sync/pull/2) pull request and present in subsequent releases since I did not test it thoroughly enough before merging. The latest release fixed that bug and brought the downloader back to its intended behavior.

I do agree that there should be a feature that lets the user toggle between folder sorting and simply downloading to a single directory -- something like a checkbox on the main screen. I will add that option and close this issue after it has been included in the next release.

Thanks.

**Comment by StephenCasella** [comment] 2015-05-09 01:29
Accidentally prematurely closed. Reopening until I implement and release the toggle.

**Comment by erwinkramer** [comment] 2015-09-05 13:16
Hi @BenjaminKobjolke, 

Please check out my fork at https://github.com/erwinkramer/SoundCloud-Playlist-Sync/releases. I added the toggle and improved a bunch of other things. You'll surely like it!

**Closed** 2016-06-03 16:02 UTC
